language: python

# Python versions for matrix
python:
  - "2.7"
  - "2.6"

# Django versions for matrix
env:
  - DJANGO_VERSION=1.4.6
  - DJANGO_VERSION=1.5.3

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -q Django==$DJANGO_VERSION --use-mirrors

# command to run tests, e.g. python setup.py test
script:
  - python manage.py test
