language: python

# Python versions for matrix
python:
  - "2.7"
  - "2.6"
  - "3.2"
  - "3.3"

# Django versions for matrix
env:
  - DJANGO_VERSION=1.4.6
  - DJANGO_VERSION=1.5.3
  - DJANGO_VERSION=1.6.0

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -q Django==$DJANGO_VERSION --use-mirrors

# Command to run tests, e.g. python setup.py test
script:
  - python manage.py test

# Support Python3 only with Django 1.6
matrix:
  exclude:
    - python: "3.2"
      env: DJANGO="django==1.4.6"
    - python: "3.2"
      env: DJANGO="django==1.5.3"
    - python: "3.3"
      env: DJANGO="django==1.4.6"
    - python: "3.3"
      env: DJANGO="django==1.5.3"
